FROM nginx:1.29-alpine

COPY deploy/aliyun/nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html admin.html judge.html leaderboard.html start-checkin.html web-nfc-timing-test.html timing-api.js /usr/share/nginx/html/
COPY assets /usr/share/nginx/html/assets

EXPOSE 8080
