alter table public.race_profiles
  add column if not exists is_template boolean not null default false;

update public.race_profiles
set is_template = race_id in ('fitmonster-hyrox-single', 'hoka-race');

create table if not exists public.race_admin_actions (
  id bigint generated by default as identity primary key,
  race_id text not null references public.race_profiles(race_id) on delete cascade,
  action text not null,
  reason text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint race_admin_actions_action_check check (action in ('finalize', 'reopen')),
  constraint race_admin_actions_reason_check
    check (char_length(btrim(reason)) between 2 and 500)
);

create index if not exists race_admin_actions_race_created_idx
  on public.race_admin_actions (race_id, created_at desc, id desc);

alter table public.race_admin_actions enable row level security;

revoke all on public.race_admin_actions from anon, authenticated;
grant select, insert, update on public.race_admin_actions to anon;

create policy race_admin_actions_server_select
  on public.race_admin_actions
  for select
  to anon
  using ((select private.timing_api_authorized()));

create policy race_admin_actions_server_insert
  on public.race_admin_actions
  for insert
  to anon
  with check ((select private.timing_api_authorized()));

create policy race_admin_actions_server_update
  on public.race_admin_actions
  for update
  to anon
  using ((select private.timing_api_authorized()))
  with check ((select private.timing_api_authorized()));
