create table if not exists public.judge_station_accounts (
  id bigint generated by default as identity primary key,
  race_id text not null,
  role text not null,
  username text not null,
  password_hash text not null,
  password_salt text not null,
  display_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint judge_station_accounts_role_check
    check (role in ('start', 'station_1', 'station_2', 'station_3', 'station_4', 'station_5')),
  constraint judge_station_accounts_race_role_key unique (race_id, role),
  constraint judge_station_accounts_race_username_key unique (race_id, username)
);

create index if not exists judge_station_accounts_race_active_idx
  on public.judge_station_accounts (race_id, active, role);

alter table public.judge_station_accounts enable row level security;
revoke all on public.judge_station_accounts from anon, authenticated;
grant select, insert, update on public.judge_station_accounts to anon;

drop policy if exists judge_station_accounts_server_access
  on public.judge_station_accounts;
create policy judge_station_accounts_server_access
  on public.judge_station_accounts
  for all
  to anon
  using ((select private.timing_api_authorized()))
  with check ((select private.timing_api_authorized()));
