create table if not exists public.device_bindings (
  id bigint generated by default as identity primary key,
  race_id text not null references public.race_profiles(race_id) on delete cascade,
  device_id text not null,
  assignment text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint device_bindings_device_id_check check (length(device_id) between 1 and 100),
  constraint device_bindings_assignment_check check (length(assignment) between 1 and 100),
  constraint device_bindings_device_unique unique (race_id, device_id),
  constraint device_bindings_assignment_unique unique (race_id, assignment)
);

create index if not exists device_bindings_race_idx
  on public.device_bindings (race_id, updated_at desc);

alter table public.device_bindings enable row level security;
revoke all on public.device_bindings from anon, authenticated;
